name: ARM plugin
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'releases/**'
      - 'master'
    paths:
      - 'modules/arm_plugin/**'
  push:
    branches:
      - 'master'
      - 'github-actions'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  Build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-arm64']
        # os: ['macos-arm64', 'windows-latest-8-cores', 'ubuntu-20.04-16-cores']
    runs-on: ['self-hosted', 'macOS']
    env:
      BUILD_TYPE: Release
      CCACHE_DIR: /Users/sandye51/actions-runner/build_cache
      CCACHE_MAXSIZE: 10G
      CMAKE_OSX_DEPLOYMENT_TARGET: 11.0
      INSTALL_DIR: "$GITHUB_WORKSPACE/install"
      INSTALL_TEST_DIR: "$INSTALL_DIR/tests"
      SAMPLES_INSTALL_DIR: "$INSTALL_DIR/samples"
      BUILD_DIR: "$GITHUB_WORKSPACE/build"
    steps:
      - name: Clone OpenVINO with cache
        if: runner.os == 'macOS'
        run: |
          rm -fr openvino
          git clone --reference /Users/sandye51/actions-runner/openvino.reference/ https://github.com/openvinotoolkit/openvino.git
          cd $GITHUB_WORKSPACE/openvino && \
             git submodule init && \
             git submodule update --reference /Users/sandye51/actions-runner/submodules.reference --jobs 4

      - name: Clone OpenVINO
        if: runner.os != 'macOS'
        run: |
          git clone https://github.com/openvinotoolkit/openvino.git
          cd $GITHUB_WORKSPACE/openvino && git submodule update --init

      #
      # Dependencies
      #

      - uses: actions/setup-python@v4
        if: runner.os != 'macOS'
        id: cp310
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            openvino/src/bindings/python/wheel/requirements-dev.txt
            openvino/src/bindings/python/requirements.txt
            openvino/src/bindings/python/src/compatibility/openvino/requirements-dev.txt
            openvino/src/frontends/paddle/tests/requirements.txt
            openvino/src/frontends/onnx/tests/requirements.txt
            openvino/src/frontends/tensorflow/tests/requirements.txt

      - name: Install python dependencies
        run: |
          # For Python API
          python3 -m pip install --upgrade pip
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/src/bindings/python/wheel/requirements-dev.txt"
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/src/bindings/python/requirements.txt"
          # For running Python API tests
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/src/bindings/python/src/compatibility/openvino/requirements-dev.txt"
          # For running Paddle frontend unit tests
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/src/frontends/paddle/tests/requirements.txt"
          # For running ONNX frontend unit tests
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/src/frontends/onnx/tests/requirements.txt"
          # For running TensorFlow frontend unit tests
          # python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/src/frontends/tensorflow/tests/requirements.txt"

      - name: Install MO dependencies
        run: |
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/tools/mo/requirements_mxnet.txt"
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/tools/mo/requirements_caffe.txt"
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/tools/mo/requirements_kaldi.txt"
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/tools/mo/requirements_onnx.txt"
          # python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/tools/mo/requirements_tf2.txt"
          python3 -m pip install -r "$GITHUB_WORKSPACE/openvino/tools/mo/requirements_dev.txt"

      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: sudo "$GITHUB_WORKSPACE/openvino/install_build_dependencies.sh"

      #
      # Build
      #

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: CMake configure
        id: cmake-configure
        run: |
          echo "::group::Define cmake arguments"
          if [[ "$RUNNER_OS" == "macOS" ]] ; then
            cmake_args=(-DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.CMAKE_OSX_DEPLOYMENT_TARGET }})
            cmake_args+=(-DARM_COMPUTE_SCONS_JOBS=4)
          fi
          echo "::endgroup::"

          echo "::group::CMake configure"
          cmake "${cmake_args[@]}" \
            -DENABLE_CPPLINT=OFF \
            -DENABLE_NCC_STYLE=OFF \
            -DENABLE_TESTS=ON \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DENABLE_PYTHON=ON \
            -DENABLE_WHEEL=ON \
            -DENABLE_TESTS=ON \
            -G Ninja \
            -S "$GITHUB_WORKSPACE/openvino" \
            -B "$BUILD_DIR"
          echo "::endgroup::"

      - name: CMake build & install
        run: |
          echo "::group::Clean ccache stats"
          export CCACHE_DIR=${{ env.CCACHE_DIR }}
          export CCACHE_MAXSIZE=${{ env.CCACHE_MAXSIZE }}
          ccache --zero-stats --show-config
          echo "::endgroup::"

          echo "::group::Cmake build logs"
          cmake --build "$BUILD_DIR" --parallel ${{ steps.cpu-cores.outputs.count }} \
            --config ${{ env.BUILD_TYPE }} || exit 1
          echo "::endgroup::"

          echo "::group::Show ccache stats"
          ccache --show-stats
          echo "::endgroup::"

          echo "::group::CMake install"
          cmake --install "$BUILD_DIR" --strip --config Release --prefix "$GITHUB_WORKSPACE/install"
          cmake --install "$BUILD_DIR" --strip --config Release --prefix "$GITHUB_WORKSPACE/install" --component python_wheels
          cmake --install "$BUILD_DIR" --strip --config Release --prefix "$GITHUB_WORKSPACE/install" --component tests
          echo "::endgroup::"

      - name: Build cpp samples
        run: $SAMPLES_INSTALL_DIR/cpp/build_samples.sh -i $INSTALL_DIR -b $BUILD_DIR/cpp_samples

      - name: Build c samples
        run: $SAMPLES_INSTALL_DIR/c/build_samples.sh -i $INSTALL_DIR -b $BUILD_DIR/c_samples

      - name: 'Clean build dir'
        run: rm -fr $BUILD_DIR

      #
      # Python tests
      #

      - name: 'Install Python wheels'
        run: python3 -m pip install openvino-dev --find-links="$GITHUB_WORKSPACE/install/tools"

      - name: nGraph and IE Python Bindings Tests
        run: |
          python3 -m pytest -s $INSTALL_TEST_DIR/pyngraph \
            --junitxml=$INSTALL_TEST_DIR/TEST-Pyngraph.xml \
            --ignore=$INSTALL_TEST_DIR/pyngraph/tests/test_onnx/test_zoo_models.py \
            --ignore=$INSTALL_TEST_DIR/pyngraph/tests/test_onnx/test_backend.py

      - name: Python API 2.0 Tests
        run: |
          # For python imports to import pybind_mock_frontend
          export PYTHONPATH=$INSTALL_TEST_DIR:$(INSTALL_DIR)/python/python3.10:$PYTHONPATH
          python3 -m pytest -sv $INSTALL_TEST_DIR/pyopenvino \
            --junitxml=$INSTALL_TEST_DIR/TEST-Pyngraph.xml \
            --ignore=$INSTALL_TEST_DIR/pyopenvino/tests/test_utils/test_utils.py \
            --ignore=$INSTALL_TEST_DIR/pyopenvino/tests/test_onnx/test_zoo_models.py \
            --ignore=$INSTALL_TEST_DIR/pyopenvino/tests/test_onnx/test_backend.py

      - name: Model Optimizer UT
        run: python3 -m pytest -s $INSTALL_TEST_DIR/mo/unit_tests --junitxml=$INSTALL_TEST_DIR/TEST-ModelOptimizer.xml

      #
      # C++ tests
      #

      - name: OpenVINO Core unit tests
        run: $INSTALL_TEST_DIR/ov_core_unit_tests --gtest_print_time=1 --gtest_filter=-*IE_GPU* --gtest_output=xml:$INSTALL_TEST_DIR/TEST-NGraphUT.xml

      - name: OpenVINO Inference functional tests
        run: $INSTALL_TEST_DIR/ov_inference_functional_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-InferenceFunc.xml

      - name: OpenVINO Inference unit tests
        run: $INSTALL_TEST_DIR/ov_inference_unit_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-InferenceUnit.xml

      - name: Low Precision Transformations Tests
        run: $INSTALL_TEST_DIR/ov_lp_transformations_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-LpTransformations.xml

      - name: OpenVINO Conditional compilation tests
        run: $INSTALL_TEST_DIR/ov_conditional_compilation_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-ConditionalCompilation.xml

      - name: IR frontend tests
        run: $INSTALL_TEST_DIR/ov_ir_frontend_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-IRFrontend.xml

      - name: PaddlePaddle frontend tests
        run: $INSTALL_TEST_DIR/paddle_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-PaddleTests.xml

      - name: ONNX frontend tests
        run: $INSTALL_TEST_DIR/ov_onnx_frontend_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-ONNXFrontend.xml

      - name: TensorFlow Common tests
        run: $INSTALL_TEST_DIR/ov_tensorflow_common_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-TensorFlowCommonFrontend.xml

      - name: TensorFlow frontend tests
        run: $INSTALL_TEST_DIR/ov_tensorflow_frontend_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-TensorFlowFrontend.xml

      - name: TensorFlow Lite frontend tests
        run: $INSTALL_TEST_DIR/ov_tensorflow_lite_frontend_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-TensorFlowLiteFrontend.xml

      - name: Transformations Tests
        run: $INSTALL_TEST_DIR/ov_transformations_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-Transformations.xml

      - name: Common test utils tests
        run: $INSTALL_TEST_DIR/commonUtilsTests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-commonUtilsTests.xml

      - name: CPU plugin unit tests
        run: $INSTALL_TEST_DIR/ov_cpu_unit_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-CPUUnitTests.xml

      - name: GNA plugin unit tests
        run: $INSTALL_TEST_DIR/ov_gna_unit_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-GNAUnitTests.xml

      - name: MULTI / AUTO plugin unit tests
        run: $INSTALL_TEST_DIR/ieMultiPluginUnitTests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-MultiAutoUnitTests.xml

      - name: Template plugin tests
        run: $INSTALL_TEST_DIR/ov_template_func_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-TemplateFuncTests.xml

      - name: Inference Engine C API tests
        run: $INSTALL_TEST_DIR/InferenceEngineCAPITests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-InferenceEngineCAPITests.xml

      - name: OpenVINO C API tests
        run: $INSTALL_TEST_DIR/ov_capi_tests --gtest_print_time=1 --gtest_output=xml:$INSTALL_TEST_DIR/TEST-OpenVINOCAPITests.xml
