name: ARM plugin
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'releases/**'
      - 'master'
    paths:
      - 'modules/arm_plugin/**'
  push:
    branches:
      - 'master'
      - 'github-actions'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  Build:
    defaults:
      run:
        shell: bash
    runs-on: macos-arm64
    steps:
      - name: Clone OpenVINO with cache
        if: runner.os == 'macOS'
        run: |
          git clone https://github.com/openvinotoolkit/openvino.git --reference $GITHUB_WORKSPACE/submodule_cache
          cd $GITHUB_WORKSPACE/openvino && git submodule update --init --reference $GITHUB_WORKSPACE/submodule_cache

      - name: Clone OpenVINO
        if: runner.os != 'macOS'
        run: |
          git clone https://github.com/openvinotoolkit/openvino.git
          cd $GITHUB_WORKSPACE/openvino && git submodule update --init

      - uses: actions/setup-python@v4
        id: cp310
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            src/bindings/python/wheel/requirements-dev.txt
            src/bindings/python/requirements.txt
            src/bindings/python/src/compatibility/openvino/requirements-dev.txt
            src/frontends/paddle/tests/requirements.txt
            src/frontends/onnx/tests/requirements.txt
            src/frontends/tensorflow/tests/requirements.txt

      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: |
          "$GITHUB_WORKSPACE/openvino/install_build_dependencies.sh"

      - name: CMake configure
        id: cmake-configure
        run: |
          echo "::group::Define cmake arguments"
          if [[ "$RUNNER_OS" == "macOS" ]] ; then
            cmake_args=(-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0)
            cmake_args+=(-DARM_COMPUTE_SCONS_JOBS=4)
          fi
          echo "::endgroup::"

          echo "::group::Clean ccache stats"
          ccache --zero-stats --max-size=50G --show-config
          echo "::endgroup::"

          echo "::group::CMake configure"
          cmake "${cmake_args[@]}" \
            -DENABLE_TESTS=ON \
            -DENABLE_CPPLINT=OFF \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DENABLE_PYTHON=ON \
            -DENABLE_WHEEL=ON \
            -DENABLE_TESTS=ON \
            -S "$GITHUB_WORKSPACE/openvino" \
            -B "$GITHUB_WORKSPACE/build"
          echo "::endgroup::"

      - name: CMake build & install
        run: |
          echo "::group::Cmake build logs"
          cmake --build "$GITHUB_WORKSPACE/build" --parallel --config Release
          cmake --install "$GITHUB_WORKSPACE/build" --strip --config Release --prefix "$GITHUB_WORKSPACE/install"
          echo "::endgroup::"

          echo "::group::Show ccache stats"
          ccache --show-stats
          echo "::endgroup::"

      - name: 'Install wheel packages'
        run: cmake --install "$GITHUB_WORKSPACE/build" --strip --config Release --prefix "$GITHUB_WORKSPACE/install" --component python_wheels
      
      - name: 'Install Python wheels'
        run: python3 -m pip install openvino-dev --find-links="$GITHUB_WORKSPACE/install/tools"

      - name: Run core tests
        run:
          cd "$GITHUB_WORKSPACE/install"
          source setupvars.sh
          ./tests/ov_core_unit_tests
