name: ARM plugin
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'releases/**'
      - 'master'
    paths:
      - 'modules/arm_plugin/**'
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  Build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "macos-latest"
            cmake-options: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - os: "windows-latest"
            cmake-options: "-A ARM64"
          - os: "ubuntu-latest"
            cmake-options: "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/../openvino/cmake/arm64.toolchain.cmake"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v3
        with:
          repository: 'openvinotoolkit/openvino'
          path: ../openvino
          ref: 'master'
          submodules: true

      - name: Clone OpenVINO Contrib
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup scons
        run: python3 -m pip install scons

      - name: Install cross-compiler
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y crossbuild-essential-arm64

      - name: CMake config
        shell: bash
        run: |
          cmake \
            ${{ matrix.cmake-options }} \
            -S '${{ github.workspace }}/../openvino' \
            -DENABLE_TESTS=ON \
            -DENABLE_CPPLINT=OFF \
            -DENABLE_INTEL_MYRIAD_COMMON=OFF \
            -DOPENVINO_EXTRA_MODULES='${{ github.workspace }}/modules/arm_plugin'

      - name: CMake build
        run: cmake --build . --parallel --config Release
